#!/bin/bash

echo "=================================================="
echo "🚀 LEO ORBITAL DOCKING - SCENARIO SUMMARY"
echo "=================================================="
echo ""
echo "📍 INITIAL POSITIONS:"
echo "   Chaser (Blue):  (0, 0, 0) at origin"
echo "   Dock (Orange):  (15, 5, 3) - ~16 meters away"
echo ""
echo "🎯 MISSION PARAMETERS:"
echo "   Initial Distance: ~16 meters"
echo "   Dock Speed: 0.5 m/s (random direction)"
echo "   Success Threshold: 0.5 meters"
echo "   Max Thruster Force: 20 N"
echo ""
echo "⚙️  CONTROLLER TUNING:"
echo "   Proportional Gain (kp): 2.0"
echo "   Derivative Gain (kd): 1.2"
echo ""
echo "🎮 WHAT TO EXPECT:"
echo "   1. Dock starts moving with random velocity"
echo "   2. Chaser activates thrusters"
echo "   3. Pursuit begins - watch the chase!"
echo "   4. Distance decreases as chaser intercepts"
echo "   5. Success when within 0.5m"
echo ""
echo "📊 WATCH THE CONSOLE FOR:"
echo "   - Distance updates every 0.2 seconds"
echo "   - Applied force vectors"
echo "   - Velocity information"
echo "   - Success notification"
echo ""
echo "🔧 TO MAKE IT HARDER/EASIER:"
echo "   Edit worlds/leo.sdf:"
echo "   - Increase dock_init_speed for more challenge"
echo "   - Change dock pose for different starting positions"
echo "   - Adjust kp/kd for different approach behavior"
echo "   - Modify max_force to limit thruster power"
echo ""
echo "=================================================="
echo "Press ENTER to launch simulation..."
read

./run_simulation.sh
